import data from './generated/drafts.json';
import type { Locale } from './catalogue';
export const detailCopy = {
"fr": {"unknown": "Non précisé dans la source", "browse": "Voir les épisodes", "submitted": "Playlist fournie (Peuples et paysages)", "missingTitle": "Titre indisponible", "back": "Tous les programmes", "videos": "vidéos", "watch": "Voir sur YouTube", "source": "Playlist originale", "previous": "Précédent", "next": "Suivant", "page": "Page", "original": "Titre original sur YouTube", "summary": "L’essentiel", "who": "Qui", "what": "Quoi", "when": "Quand", "where": "Où", "why": "Contexte", "how": "Approche narrative", "note": "Résumé établi à partir du titre et de la description officiels. Les informations absentes de la source ne sont pas supposées.", "shared": "Les deux parties partagent la même description officielle ; les détails propres à chaque épisode restent à compléter.", "person": "À propos de cette personne", "pending": "Le résumé en français est en préparation. La vidéo originale est disponible sur YouTube.", "videoBack": "Retour aux épisodes", "unavailable": "Les vidéos masquées ou indisponibles sur YouTube ne peuvent pas être présentées ici."},
"es": {"unknown": "No consta en la fuente", "browse": "Ver episodios", "submitted": "Lista facilitada (Personas y lugares)", "missingTitle": "Título no disponible", "back": "Todos los programas", "videos": "vídeos", "watch": "Ver en YouTube", "source": "Lista original", "previous": "Anterior", "next": "Siguiente", "page": "Página", "original": "Título original en YouTube", "summary": "De un vistazo", "who": "Quién", "what": "Qué", "when": "Cuándo", "where": "Dónde", "why": "Contexto", "how": "Cómo se cuenta", "note": "Resumen elaborado a partir del título y la descripción oficiales. Los datos que no figuran en la fuente se indican como desconocidos.", "shared": "Ambas partes comparten la descripción oficial; los detalles de cada episodio están pendientes.", "person": "Sobre esta persona", "pending": "El resumen en español está en preparación. Puede ver el vídeo original en YouTube.", "videoBack": "Volver a los episodios", "unavailable": "Los vídeos ocultos o no disponibles en YouTube no se muestran aquí."},
"hi": {"unknown": "स्रोत में उल्लेख नहीं", "browse": "एपिसोड देखें", "submitted": "उपलब्ध कराई गई प्लेलिस्ट (लोग और स्थान)", "missingTitle": "वीडियो का शीर्षक उपलब्ध नहीं", "back": "सभी कार्यक्रम", "videos": "वीडियो", "watch": "YouTube पर देखें", "source": "मूल प्लेलिस्ट", "previous": "पिछला", "next": "अगला", "page": "पृष्ठ", "original": "YouTube का मूल शीर्षक", "summary": "एक नज़र में", "who": "कौन", "what": "क्या", "when": "कब", "where": "कहाँ", "why": "पृष्ठभूमि", "how": "कहने का तरीका", "note": "यह सार आधिकारिक शीर्षक और विवरण पर आधारित है। स्रोत में न दिए गए विवरण का अनुमान नहीं लगाया गया है।", "shared": "दोनों भागों का आधिकारिक विवरण एक है; हर भाग का अलग विवरण अभी तैयार किया जा रहा है।", "person": "इस व्यक्ति के बारे में", "pending": "हिन्दी सार तैयार किया जा रहा है। मूल वीडियो YouTube पर देख सकते हैं।", "videoBack": "एपिसोड सूची पर लौटें", "unavailable": "YouTube पर छिपे या अनुपलब्ध वीडियो यहाँ नहीं दिखाए जा सकते।"},

 he: {"unknown": "לא צוין במקור", "browse": "לפרקים", "submitted": "רשימת הצפייה שסופקה (אנשים ומקומות)", "missingTitle": "כותרת הסרטון אינה זמינה", "back": "כל התוכניות", "videos": "סרטונים", "watch": "לצפייה ב־YouTube", "source": "רשימת הצפייה המקורית", "previous": "הקודם", "next": "הבא", "page": "עמוד", "original": "הכותרת המקורית ב־YouTube", "summary": "במבט קצר", "who": "מי", "what": "מה", "when": "מתי", "where": "היכן", "why": "רקע", "how": "דרך הסיפור", "note": "התקציר מבוסס על הכותרת והתיאור הרשמיים. פרטים שלא נמסרו במקור מסומנים כלא ידועים.", "shared": "לשני החלקים תיאור רשמי משותף; פירוט נפרד לכל פרק נמצא בהכנה.", "person": "על הדמות", "pending": "התקציר בעברית נמצא בהכנה. ניתן לצפות בסרטון המקורי ב־YouTube.", "videoBack": "בחזרה לפרקים", "unavailable": "סרטונים ש־YouTube מסתיר אינם מופיעים כאן."},
  'zh-Hant': {
    unknown: '資料未載明',
    browse: '瀏覽影片',
    submitted: '提供的原清單（人文地理）',
    missingTitle: '影片標題未提供',
    back: '返回節目目錄',
    videos: '部影片',
    watch: '在 YouTube 觀看',
    source: '原播放清單',
    previous: '上一頁',
    next: '下一頁',
    page: '頁',
    original: 'YouTube 影片標題',
    summary: '一分鐘了解',
    who: '人物',
    what: '內容',
    when: '時間',
    where: '地點',
    why: '緣由',
    how: '敘事方式',
    note: '根據官方影片標題與說明整理。來源未提供的細節標示為資料未載明。',
    shared: '上下集共用官方簡介；分集細節尚待補充。',
    person: '人物資料',
    pending: '本片摘要整理中。可先前往 YouTube 觀看原片。',
    videoBack: '返回影片目錄',
    unavailable: 'YouTube 另有隱藏影片，暫無法列出。',
  },
  'zh-Hans': {
    unknown: '资料未载明',
    browse: '浏览影片',
    submitted: '提供的原列表（人文地理）',
    missingTitle: '影片标题未提供',
    back: '返回节目目录',
    videos: '部影片',
    watch: '在 YouTube 观看',
    source: '原播放列表',
    previous: '上一页',
    next: '下一页',
    page: '页',
    original: 'YouTube 影片标题',
    summary: '一分钟了解',
    who: '人物',
    what: '内容',
    when: '时间',
    where: '地点',
    why: '缘由',
    how: '叙事方式',
    note: '根据官方影片标题与说明整理。来源未提供的细节标示为资料未载明。',
    shared: '上下集共用官方简介；分集细节尚待补充。',
    person: '人物资料',
    pending: '本片摘要整理中。可先前往 YouTube 观看原片。',
    videoBack: '返回影片目录',
    unavailable: 'YouTube 另有隐藏影片，暂无法列出。',
  },
  en: {
    unknown: 'Not specified by the source',
    browse: 'Browse episodes',
    submitted: 'Submitted playlist (People & Places)',
    missingTitle: 'Video title unavailable',
    back: 'All programmes',
    videos: 'videos',
    watch: 'Watch on YouTube',
    source: 'Original playlist',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    original: 'Title supplied by YouTube',
    summary: 'At a glance',
    who: 'Who',
    what: 'What',
    when: 'When',
    where: 'Where',
    why: 'Why',
    how: 'How',
    note: 'Drafted from the official video title and description. Unspecified details are marked as unknown.',
    shared: 'Both parts share an official description; episode-specific details are still being prepared.',
    person: 'About this person',
    pending:
      'The summary is being prepared. You can watch the original video on YouTube.',
    videoBack: 'Back to episodes',
    unavailable:
      'YouTube also hides unavailable videos, which cannot be listed here.',
  },
  ja: {
    unknown: '資料に記載なし',
    browse: 'エピソード一覧',
    submitted: '提供された元のリスト（人文地理）',
    missingTitle: '動画タイトル未取得',
    back: 'すべての番組',
    videos: '本の動画',
    watch: 'YouTube で見る',
    source: '元の再生リスト',
    previous: '前へ',
    next: '次へ',
    page: 'ページ',
    original: 'YouTube のタイトル',
    summary: 'ひと目でわかる',
    who: '人物',
    what: '内容',
    when: '時期',
    where: '場所',
    why: '背景',
    how: '語り方',
    note: '公式動画のタイトルと説明に基づく草稿です。出典にない詳細は記載なしとしています。',
    shared: '前後編は同じ公式説明を共有しています。各編の詳細は準備中です。',
    person: '人物について',
    pending:
      'この動画の紹介文を準備しています。YouTube で本編をご覧いただけます。',
    videoBack: 'エピソード一覧へ',
    unavailable: 'YouTube 上で非公開の動画は、ここには表示できません。',
  },
};
export type SixField = 'who' | 'what' | 'when' | 'where' | 'why' | 'how';
export type Draft = {
  status: string;
  editorial_scope?: string;
  fields: Partial<Record<Locale, Record<SixField, string | null>>>;
  source: string;
  people?: string[];
  recorded_at: string | null;
  recording_location: string | null;
  upload_date: string | null;
};
export const drafts: Partial<Record<string, Draft>> = data;
