export const detailCopy = {
  'zh-Hant': {
    browse: '瀏覽影片',
    submitted: '提供的原清單（人文地理）',
    missingTitle: '影片標題未提供',
    back: '返回節目目錄',
    videos: '部影片',
    watch: '在 YouTube 觀看',
    source: '原播放清單',
    previous: '上一頁',
    next: '下一頁',
    page: '頁',
    original: '影片原標題',
    summary: '一分鐘了解',
    who: '人物',
    what: '內容',
    when: '時間',
    where: '地點',
    why: '緣由',
    how: '敘事方式',
    note: '根據官方影片說明整理。拍攝日期與地點未載明。',
    person: '人物資料',
    pending: '本片摘要整理中。可先前往 YouTube 觀看原片。',
    videoBack: '返回影片目錄',
    unavailable: 'YouTube 另有隱藏影片，暫無法列出。',
  },
  'zh-Hans': {
    browse: '浏览影片',
    submitted: '提供的原列表（人文地理）',
    missingTitle: '影片标题未提供',
    back: '返回节目目录',
    videos: '部影片',
    watch: '在 YouTube 观看',
    source: '原播放列表',
    previous: '上一页',
    next: '下一页',
    page: '页',
    original: '影片原标题',
    summary: '一分钟了解',
    who: '人物',
    what: '内容',
    when: '时间',
    where: '地点',
    why: '缘由',
    how: '叙事方式',
    note: '根据官方影片说明整理。拍摄日期与地点未载明。',
    person: '人物资料',
    pending: '本片摘要整理中。可先前往 YouTube 观看原片。',
    videoBack: '返回影片目录',
    unavailable: 'YouTube 另有隐藏影片，暂无法列出。',
  },
  en: {
    browse: 'Browse episodes',
    submitted: 'Submitted playlist (People & Places)',
    missingTitle: 'Video title unavailable',
    back: 'All programmes',
    videos: 'videos',
    watch: 'Watch on YouTube',
    source: 'Original playlist',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    original: 'Original video title',
    summary: 'At a glance',
    who: 'Who',
    what: 'What',
    when: 'When',
    where: 'Where',
    why: 'Why',
    how: 'How',
    note: 'Drafted from the official video description. Recording date and location are not specified.',
    person: 'About this person',
    pending:
      'The summary is being prepared. You can watch the original video on YouTube.',
    videoBack: 'Back to episodes',
    unavailable:
      'YouTube also hides unavailable videos, which cannot be listed here.',
  },
  ja: {
    browse: 'エピソード一覧',
    submitted: '提供された元のリスト（人文地理）',
    missingTitle: '動画タイトル未取得',
    back: 'すべての番組',
    videos: '本の動画',
    watch: 'YouTube で見る',
    source: '元の再生リスト',
    previous: '前へ',
    next: '次へ',
    page: 'ページ',
    original: '動画の原題',
    summary: 'ひと目でわかる',
    who: '人物',
    what: '内容',
    when: '時期',
    where: '場所',
    why: '背景',
    how: '語り方',
    note: '公式動画の説明に基づく草稿です。撮影日時・場所は記載されていません。',
    person: '人物について',
    pending:
      'この動画の紹介文を準備しています。YouTube で本編をご覧いただけます。',
    videoBack: 'エピソード一覧へ',
    unavailable: 'YouTube 上で非公開の動画は、ここには表示できません。',
  },
};
export const drafts = {
  'anL-lcfB2y0': {
    status: 'DRAFT_FROM_OFFICIAL_DESCRIPTION',
    fields: {
      'zh-Hant': {
        who: '指揮家李德倫',
        what: '回顧個人的音樂生涯',
        when: '1938年入學、1957年歸國',
        where: '輔仁大學、蘇聯與中央樂團',
        why: '接觸交響樂後立志投身音樂',
        how: '本人以口述回顧求學與指揮經歷',
      },
      'zh-Hans': {
        who: '指挥家李德伦',
        what: '回顾个人的音乐生涯',
        when: '1938年入学、1957年归国',
        where: '辅仁大学、苏联与中央乐团',
        why: '接触交响乐后立志投身音乐',
        how: '本人以口述回顾求学与指挥经历',
      },
      en: {
        who: 'Conductor Li Delun',
        what: 'A personal account of his life in music',
        when: 'University in 1938; return to China in 1957',
        where:
          'Fu Jen University, the Soviet Union and the Central Philharmonic',
        why: 'Discovering symphonic music inspired his commitment to music',
        how: 'Li recounts his education and conducting career in his own words',
      },
      ja: {
        who: '指揮者・李徳倫',
        what: '自身の音楽人生を振り返る',
        when: '1938年の大学入学、1957年の帰国',
        where: '輔仁大学、ソ連、中央楽団',
        why: '交響楽との出会いを機に音楽の道を志す',
        how: '本人の語りで学業と指揮者としての歩みをたどる',
      },
    },
    source: 'https://www.youtube.com/watch?v=anL-lcfB2y0',
    reference: 'https://www.cnso.com.cn/zgjxyt/ldldc100h/ztindex.shtml',
    recorded_at: null,
    recording_location: null,
    upload_date: '2020-06-21',
  },
};
